// data/medicationsData.ts
export const medications = [
  { name: "Abilify", slug: "drugs-supplements/drugs/abilify", description: "Description for Abilify" },
  { name: "Actos", slug: "actos", description: "Description for Actos" },
  { name: "Acyclovir", slug: "acyclovir", description: "Description for Acyclovir" },
  { name: "Adderall", slug: "adderall", description: "Description for Adderall" },
  { name: "Allopurinol", slug: "allopurinol", description: "Description for Allopurinol" },
  { name: "Ambien", slug: "ambien", description: "Description for Ambien" },
  { name: "Amitriptyline", slug: "amitriptyline", description: "Description for Amitriptyline" },
  { name: "Amoxicillin", slug: "amoxicillin", description: "Description for Amoxicillin" },
  { name: "Atenolol", slug: "atenolol", description: "Description for Atenolol" },
  { name: "Ativan", slug: "ativan", description: "Description for Ativan" },
  { name: "Azithromycin", slug: "azithromycin", description: "Description for Azithromycin" },
  { name: "Baclofen", slug: "baclofen", description: "Description for Baclofen" },
  { name: "Bactrim", slug: "bactrim", description: "Description for Bactrim" },
  { name: "Benadryl", slug: "benadryl", description: "Description for Benadryl" },
  { name: "Benzonatate", slug: "benzonatate", description: "Description for Benzonatate" },
  { name: "Bupropion", slug: "bupropion", description: "Description for Bupropion" },
  { name: "Buspirone", slug: "buspirone", description: "Description for Buspirone" },
  { name: "Celecoxib", slug: "celecoxib", description: "Description for Celecoxib" },
  { name: "Cialis", slug: "cialis", description: "Description for Cialis" },
  { name: "Citalopram", slug: "citalopram", description: "Description for Citalopram" },
  { name: "Clindamycin", slug: "clindamycin", description: "Description for Clindamycin" },
  { name: "Concerta", slug: "concerta", description: "Description for Concerta" },
  { name: "Cyclobenzaprine", slug: "cyclobenzaprine", description: "Description for Cyclobenzaprine" },
  { name: "Cymbalta", slug: "cymbalta", description: "Description for Cymbalta" },
  { name: "Depakote", slug: "depakote", description: "Description for Depakote" },
  { name: "Dicyclomine", slug: "dicyclomine", description: "Description for Dicyclomine" },
  { name: "Dilaudid", slug: "dilaudid", description: "Description for Dilaudid" },
  { name: "Effexor", slug: "effexor", description: "Description for Effexor" },
  { name: "Emgality", slug: "emgality", description: "Description for Emgality" },
  { name: "Flagyl", slug: "flagyl", description: "Description for Flagyl" },
  { name: "Fluoxetine", slug: "fluoxetine", description: "Description for Fluoxetine" },
  { name: "Gabapentin", slug: "gabapentin", description: "Description for Gabapentin" },
  { name: "Hydrochlorothiazide", slug: "hydrochlorothiazide", description: "Description for Hydrochlorothiazide" },
  { name: "Hydrocodone-Acetaminophen", slug: "hydrocodone-acetaminophen", description: "Description for Hydrocodone-Acetaminophen" },
  { name: "Hydroxyzine", slug: "hydroxyzine", description: "Description for Hydroxyzine" },
  { name: "Ibuprofen", slug: "ibuprofen", description: "Description for Ibuprofen" },
  { name: "Keppra", slug: "keppra", description: "Description for Keppra" },
  { name: "Levothyroxine", slug: "levothyroxine", description: "Description for Levothyroxine" },
  { name: "Lexapro", slug: "lexapro", description: "Description for Lexapro" },
  { name: "Lisinopril", slug: "lisinopril", description: "Description for Lisinopril" },
  { name: "Lorazepam", slug: "lorazepam", description: "Description for Lorazepam" },
  { name: "Losartan", slug: "losartan", description: "Description for Losartan" },
  { name: "Macrobid", slug: "macrobid", description: "Description for Macrobid" },
  { name: "Meloxicam", slug: "meloxicam", description: "Description for Meloxicam" },
  { name: "Methadone", slug: "methadone", description: "Description for Methadone" },
  { name: "Methocarbamol", slug: "methocarbamol", description: "Description for Methocarbamol" },
  { name: "Methylprednisolone", slug: "methylprednisolone", description: "Description for Methylprednisolone" },
  { name: "Metronidazole", slug: "metronidazole", description: "Description for Metronidazole" },
  { name: "Morphine", slug: "morphine", description: "Description for Morphine" },
  { name: "Nortriptyline", slug: "nortriptyline", description: "Description for Nortriptyline" },
  { name: "Oxycontin", slug: "oxycontin", description: "Description for Oxycontin" },
  { name: "Pantoprazole", slug: "pantoprazole", description: "Description for Pantoprazole" },
  { name: "Percocet", slug: "percocet", description: "Description for Percocet" },
  { name: "Phentermine", slug: "phentermine", description: "Description for Phentermine" },
  { name: "Plaquenil", slug: "plaquenil", description: "Description for Plaquenil" },
  { name: "Plavix", slug: "plavix", description: "Description for Plavix" },
  { name: "Pradaxa", slug: "pradaxa", description: "Description for Pradaxa" },
  { name: "Pravastatin", slug: "pravastatin", description: "Description for Pravastatin" },
  { name: "Prednisone", slug: "prednisone", description: "Description for Prednisone" },
  { name: "Pregabalin", slug: "pregabalin", description: "Description for Pregabalin" },
  { name: "Promethazine", slug: "promethazine", description: "Description for Promethazine" },
  { name: "Risperdal", slug: "risperdal", description: "Description for Risperdal" },
  { name: "Ritalin", slug: "ritalin", description: "Description for Ritalin" },
  { name: "Savella", slug: "savella", description: "Description for Savella" },
  { name: "Seroquel", slug: "seroquel", description: "Description for Seroquel" },
  { name: "Simvastatin", slug: "simvastatin", description: "Description for Simvastatin" },
  { name: "Synthroid", slug: "synthroid", description: "Description for Synthroid" },
  { name: "Tramadol", slug: "tramadol", description: "Description for Tramadol" },
  { name: "Trazodone", slug: "trazodone", description: "Description for Trazodone" },
  { name: "Trulicity", slug: "trulicity", description: "Description for Trulicity" },
  { name: "Victoza", slug: "victoza", description: "Description for Victoza" },
  { name: "Wellbutrin", slug: "wellbutrin", description: "Description for Wellbutrin" },
];

  
  // data/supplementsData.ts
export const supplements = [
  "5-Htp",
  "Activated Charcoal",
  "Ashwagandha",
  "Astaxanthin",
  "Astragalus",
  "Berberine",
  "Biotin",
  "Bromelain",
  "Calcium",
  "Chlorella",
  "Chlorophyll",
  "Choline",
  "Chromium",
  "Coconut Oil",
  "Cod Liver Oil",
  "Colloidal Silver",
  "Conjugated Linoleic Acid",
  "Cordyceps",
  "Creatine",
  "Damiana",
  "Echinacea",
  "Emu Oil",
  "Evening Primrose Oil",
  "Fenugreek",
  "Fish Oil",
  "Folic Acid",
  "Gamma-Aminobutyric Acid",
  "Garlic",
  "Ginger",
  "Ginkgo",
  "Glucomannan",
  "Glutathione",
  "Gotu Kola",
  "Holy Basil",
  "Horny Goat Weed",
  "Hyaluronic Acid",
  "Inositol",
  "Iodine",
  "Iron",
  "Krill Oil",
  "L-Arginine",
  "L-Carnitine",
  "Lecithin",
  "Lemon Balm",
  "Licorice",
  "Lutein",
  "Maca",
  "Magnesium",
  "Maritime Pine",
  "Melatonin",
  "Moringa",
  "Oolong Tea",
  "Phenylalanine",
  "Phosphatidylserine",
  "Potassium",
  "Progesterone",
  "Propolis",
  "Pu-Erh Tea",
  "Quercetin",
  "Raspberry Ketone",
  "Rhodiola",
  "Royal Jelly",
  "Saw Palmetto",
  "Serrapeptase",
  "Slippery Elm",
  "Taurine",
  "Tea Tree Oil",
  "Tribulus",
  "Valerian",
  "Vitamin A",
  "Vitamin D",
  "Vitamin E",
  "Whey Protein",
  "Witch Hazel",
  "Xylitol",
  "Yohimbe",
];
export const articles = [
  {
    title: "Popular Weight Loss Drugs Raise Risk of More Stomach Trouble",
    source: "WebMD Health News",
  },
  {
    title: "FDA Adds Warning of Intestinal Blockages to Ozempic Label",
    source: "WebMD Health News Brief",
  },
  {
    title: "Popular OTC Decongestants Don’t Really Work, FDA Says",
    source: "WebMD Health News Brief",
  },
  {
    title: "3D-Printed Meds Customize the Dose for Sick Children",
    source: "WebMD Health News Brief",
  },
];

